package com.example.domain.core.tools

/**
 * Definition of a parameter accepted by a tool.
 */
data class ToolParameter(
    val name: String,
    val type: String, // "string", "number", "boolean", "object", "array"
    val description: String,
    val isRequired: Boolean = true,
    val enumValues: List<String> = emptyList()
)

/**
 * Metadata and schema declaration of a callable tool.
 */
data class ToolDeclaration(
    val name: String,
    val description: String,
    val parameters: List<ToolParameter> = emptyList(),
    val isSensitive: Boolean = false,
    val requiresHumanConsent: Boolean = false
)

/**
 * Input payload sent to a tool for execution.
 */
data class ToolInput(
    val toolName: String,
    val arguments: Map<String, Any?>,
    val executionId: String? = null,
    val contextAttributes: Map<String, String> = emptyMap()
)

/**
 * Output generated by a tool upon execution.
 */
data class ToolOutput(
    val content: String,
    val isTruncated: Boolean = false,
    val rawBytesCount: Long = 0L,
    val attributes: Map<String, String> = emptyMap()
)

/**
 * Categorized domain failures for tool execution.
 */
sealed interface ToolFailure {
    data class InvalidParameters(val missingOrInvalidKeys: List<String>, val reason: String) : ToolFailure
    data class PermissionDenied(val pathOrResource: String, val message: String) : ToolFailure
    data class ExecutionTimeout(val timeoutMs: Long) : ToolFailure
    data class SecurityDenied(val ruleName: String, val message: String) : ToolFailure
    data class CapabilityUnavailable(val capabilityName: String, val message: String) : ToolFailure
    data class InternalExecutionError(val message: String, val exitCode: Int? = null) : ToolFailure
}
