package com.example.domain.core.tools

import com.example.domain.core.capability.CapabilityType
import com.example.domain.core.capability.Locality
import com.example.domain.core.capability.NetworkRequirement
import com.example.domain.core.capability.SideEffectClassification

/**
 * Definition of a parameter accepted by a tool.
 *
 * ROUND-4 (Gemini 400 `properties[hunks].items: missing field`): Gemini's
 * function-declaration schema is an OpenAPI SUBSET that REQUIRES an `items`
 * element for every `type: "array"` property — an array without an item
 * schema rejects the WHOLE request with 400 INVALID_ARGUMENT (OpenAI-style
 * providers tolerate it, which is why only Gemini collapsed). The two new
 * optional fields let a catalog declare the item shape once, domain-side:
 *  - [itemType] — the JSON type of ONE array element ("string"/"object"/…);
 *  - [itemProperties] — when items are objects, their inner parameter list
 *    (rendered as `items.properties` + `items.required` on the wire).
 * Both default to "absent" so every existing declaration is unaffected.
 */
data class ToolParameter(
    val name: String,
    val type: String, // "string", "number", "boolean", "object", "array"
    val description: String,
    val isRequired: Boolean = true,
    val enumValues: List<String> = emptyList(),
    val itemType: String? = null,
    val itemProperties: List<ToolParameter> = emptyList()
)

/**
 * Metadata, schema declaration, and structured capability descriptors of a callable tool.
 */
data class ToolDeclaration(
    val name: String,
    val description: String,
    val parameters: List<ToolParameter> = emptyList(),
    val isSensitive: Boolean = false,
    val requiresHumanConsent: Boolean = false,
    val providedCapabilities: Set<CapabilityType> = setOf(CapabilityType.TOOL_EXECUTION),
    val networkRequirement: NetworkRequirement = NetworkRequirement.LOCAL_ONLY,
    val sideEffects: SideEffectClassification = SideEffectClassification.READ_ONLY,
    val requiredPermissions: List<String> = emptyList(),
    val locality: Locality = Locality.LOCAL_ON_DEVICE
)


/**
 * Input payload sent to a tool for execution.
 *
 * GAP-02 part 2 (Design Closure 2026): `principalId` carries the EXECUTING
 * principal (the agent id on agent-driven paths) so governed tools can
 * attribute their admission audit rows to the real actor instead of an
 * anonymous placeholder. Null = the caller could not attribute the call.
 */
data class ToolInput(
    val toolName: String,
    val arguments: Map<String, Any?>,
    val executionId: String? = null,
    val principalId: String? = null,
    val contextAttributes: Map<String, String> = emptyMap()
)

/**
 * Output generated by a tool upon execution.
 */
data class ToolOutput(
    val content: String,
    val isTruncated: Boolean = false,
    val rawBytesCount: Long = 0L,
    val attributes: Map<String, String> = emptyMap()
)

/**
 * Categorized domain failures for tool execution.
 */
sealed interface ToolFailure {
    data class InvalidParameters(val missingOrInvalidKeys: List<String>, val reason: String) : ToolFailure
    data class PermissionDenied(val pathOrResource: String, val message: String) : ToolFailure
    data class ExecutionTimeout(val timeoutMs: Long) : ToolFailure
    data class SecurityDenied(val ruleName: String, val message: String) : ToolFailure
    data class CapabilityUnavailable(val capabilityName: String, val message: String) : ToolFailure
    data class InternalExecutionError(val message: String, val exitCode: Int? = null) : ToolFailure
}
