package com.example.domain.core.events

import com.example.domain.core.DegradedReason
import com.example.domain.core.Outcome
import com.example.domain.core.agent.AgentId
import com.example.domain.core.tools.ToolFailure

/**
 * Immutable operational events emitted during execution.
 *
 * Streaming is a first-class operational lifecycle event channel,
 * not just raw string chunk delivery.
 */
sealed interface ExecutionEvent {
    val executionId: String
    val timestampMs: Long

    /**
     * Fired when an agent task execution begins.
     */
    data class Started(
        override val executionId: String,
        val agentId: AgentId,
        val modelId: String,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when CBR-MDP Decision Engine selects an action.
     */
    data class DecisionMade(
        override val executionId: String,
        val decision: com.example.domain.core.decision.DecisionResult,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when an action execution begins within the closed-loop task lifecycle.
     */
    data class ActionStarted(
        override val executionId: String,
        val action: com.example.domain.core.decision.DecisionAction,
        val stepIndex: Int,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when an action finishes execution with success.
     */
    data class ActionCompleted(
        override val executionId: String,
        val action: com.example.domain.core.decision.DecisionAction,
        val outputSummary: String,
        val observation: com.example.domain.core.decision.EnvironmentObservation,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when an action execution fails, feeding into the replanning/retry feedback loop.
     */
    data class ActionFailed(
        override val executionId: String,
        val action: com.example.domain.core.decision.DecisionAction,
        val errorDescription: String,
        val observation: com.example.domain.core.decision.EnvironmentObservation,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when an observation is fed back to the decision engine.
     */
    data class ObservationRecorded(
        override val executionId: String,
        val observation: com.example.domain.core.decision.EnvironmentObservation,
        val updatedUncertainty: Float,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when the closed-loop orchestrator initiates a replan following degradation or failure.
     */
    data class Replanned(
        override val executionId: String,
        val reason: String,
        val stepIndex: Int,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Incremental delta text output generated by the model.
     */
    data class ContentChunk(
        override val executionId: String,
        val deltaText: String,
        val sequenceIndex: Int,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when a tool invocation is required.
     */
    data class ToolRequested(
        override val executionId: String,
        val callId: String,
        val toolName: String,
        val argumentsJson: String,
        val isSensitive: Boolean = false,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when a tool finishes execution with an explicit Outcome.
     */
    data class ToolResult(
        override val executionId: String,
        val callId: String,
        val toolName: String,
        val outcome: Outcome<String, ToolFailure>,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when execution enters or encounters a degraded state.
     */
    data class Degraded(
        override val executionId: String,
        val reason: DegradedReason,
        val message: String,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when execution encounters an error.
     */
    data class Error(
        override val executionId: String,
        val failureCode: String,
        val message: String,
        val isFatal: Boolean = true,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Real-time telemetry update for token expenditure and budget tracking.
     */
    data class UsageBudgetUpdate(
        override val executionId: String,
        val promptTokens: Int,
        val completionTokens: Int,
        val totalSessionTokens: Int,
        val remainingBudgetTokens: Int,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted upon successful or degraded completion of the entire execution.
     */
    data class Completed(
        override val executionId: String,
        val finalText: String,
        val totalDurationMs: Long,
        val isDegraded: Boolean = false,
        val degradedReason: DegradedReason? = null,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent

    /**
     * Emitted when execution was cancelled by the user or system.
     */
    data class Cancelled(
        override val executionId: String,
        val reason: String,
        override val timestampMs: Long = System.currentTimeMillis()
    ) : ExecutionEvent
}
