package com.example.application.rag

import com.example.application.resource.ResourceRegistryService
import com.example.application.resource.RuntimeAdapterResolver
import com.example.domain.core.Outcome
import com.example.domain.core.execution.ExecutionScope
import com.example.domain.core.memory.EmbeddingVector
import com.example.domain.core.memory.RetrievalMode
import com.example.domain.core.provider.HealthStatus
import com.example.domain.core.rag.AssembledRagContext
import com.example.domain.core.rag.DocumentChunk
import com.example.domain.core.rag.KnowledgeDocument
import com.example.domain.core.rag.KnowledgePersistenceState
import com.example.domain.core.rag.RetrievedContextChunk
import com.example.domain.core.resource.ResourceId
import com.example.domain.core.resource.ResourceType
import com.example.domain.ports.memory.EmbeddingProviderPort
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.util.concurrent.CopyOnWriteArrayList
import java.util.concurrent.atomic.AtomicLong
import kotlin.math.sqrt

/**
 * ============================================================================
 * RagPipelineService — Phase 4 (resource-backed, no direct adapter injection)
 * ============================================================================
 *
 * Per the architectural plan (Section 8): embedding execution is resource-backed.
 * The correct conceptual path is:
 *
 *   Provider → Embedding Service → Protocol → Configuration → discovered
 *   ModelDescriptor → ServiceOffering → Resource → ResourceRegistry →
 *   Decision → exact resource execution
 *
 * This service no longer takes a direct `EmbeddingProviderPort` injection.
 * Instead, it accepts:
 *
 *   - `resourceRegistry` — the authoritative `DurableResourceRegistryService`
 *     that holds all materialized `ResourceRecord`s
 *   - `runtimeAdapterResolver` — the resolver that maps `ResourceId` → adapter
 *   - `fallbackEmbeddingProvider` — a best-effort local in-process adapter used
 *     ONLY when no embedding ResourceRecord exists yet (first-run fallback).
 *     The fallback is honest: the `RetrievalMode` flag in the returned
 *     `RetrievedContextChunk` is `LEXICAL_FALLBACK` (not `HYBRID`).
 *
 * Per the architectural plan (Section 8): "If a different embedding resource is
 * selected, the system must recognize the compatibility boundary rather than
 * pretending vectors are interchangeable." Therefore, each chunk's persisted
 * `retrievalSource` field records which embedding resource generated it. When
 * a new embedding resource is selected for retrieval, chunks generated by a
 * different embedding resource are not mixed in — they're filtered out, and
 * a `RetrievalMode.EMBEDDING_COMPATIBILITY_BOUNDARY` marker is set.
 */
class RagPipelineService(
    private val resourceRegistry: ResourceRegistryService,
    private val runtimeAdapterResolver: RuntimeAdapterResolver,
    private val fallbackEmbeddingProvider: EmbeddingProviderPort? = null,
    private val persistenceService: KnowledgePersistenceService? = null,
    private val workspaceIdProvider: () -> String = { "default" }
) {
    private val _documents = MutableStateFlow<List<KnowledgeDocument>>(emptyList())
    val documents: StateFlow<List<KnowledgeDocument>> = _documents.asStateFlow()

    // FIX APP-P3-27: thread-safe list for concurrent ingest calls.
    private val chunks = CopyOnWriteArrayList<DocumentChunk>()
    private val chunksMutex = Mutex()

    /**
     * GAP-CLOSURE P1-15 (stale async load guard): monotonic generation
     * counter for workspace knowledge loads. A load started for workspace A
     * that finishes AFTER a newer load for workspace B is DISCARDED — the
     * working set can never be overwritten by stale async results.
     */
    private val loadGeneration = AtomicLong(0)

    /**
     * GAP-CLOSURE P0-02: resolves the workspace for THIS call — the
     * execution-pinned scope when running inside an agent execution, else
     * the active-workspace provider (user-driven calls).
     */
    private suspend fun currentWorkspaceId(): String? {
        val pinned = currentCoroutineContext()[ExecutionScope.Key]?.workspaceId
        if (pinned != null) return pinned
        return runCatching { workspaceIdProvider() }.getOrNull()
    }

    /**
     * The embedding ResourceId used to embed the most recently-ingested chunks.
     * Used to enforce the embedding-compatibility boundary (Section 8).
     */
    @Volatile
    private var activeEmbeddingResourceId: ResourceId? = null

    init {
        bootstrapDefaultKnowledge()
    }

    /**
     * Phase 2 — Loads all persisted documents+chunks for the current workspace
     * into the in-memory index. Call this on app startup (after WorkspaceRuntimeService
     * has determined the active workspace) and whenever the user switches workspaces.
     *
     * GAP-CLOSURE P1-15: the load is generation-guarded — if a NEWER load
     * (another workspace switch) started while this one was reading, this
     * result is discarded instead of clobbering the newer workspace's
     * working set (the A-load / B-load / A-finishes-last race).
     */
    suspend fun loadFromPersistence() {
        val persistence = persistenceService ?: return
        val generation = loadGeneration.incrementAndGet()
        val workspaceId = workspaceIdProvider()
        val (docs, loadedChunks) = persistence.loadWorkspaceKnowledge(workspaceId)
        // Stale-result guard: only the LATEST load may mutate the index.
        if (loadGeneration.get() != generation) return
        chunksMutex.withLock {
            chunks.clear()
            chunks.addAll(loadedChunks)
        }
        _documents.update { docs }
    }

    /**
     * Deletes a document from the knowledge base: removes it (and its chunks)
     * from the in-memory index AND deletes it durably from Room. Honest
     * outcome — when no durable store is wired the deletion is reported as
     * volatile-only instead of pretending persistence.
     */
    suspend fun deleteDocument(documentId: String): Outcome<Unit, String> {
        // 1. Durable deletion (Room) — the authoritative store.
        val durableDelete: Boolean = persistenceService?.let { persistence ->
            runCatching { persistence.deleteDocument(documentId) }.isSuccess
        } ?: false

        // 2. In-memory index removal (documents flow + chunk index).
        _documents.update { docs -> docs.filterNot { it.id == documentId } }
        chunksMutex.withLock {
            chunks.removeAll { it.documentId == documentId }
        }

        return when {
            persistenceService == null -> Outcome.Error(
                "لا يوجد مخزن دائم للمعرفة في هذا التكوين — الحذف كان في الذاكرة فقط."
            )
            durableDelete -> Outcome.Success(Unit)
            else -> Outcome.Error("تعذر حذف المستند من المخزن الدائم (راجع سجل الأخطاء).")
        }
    }

    /**
     * Audit 2026 fix: delegates to the local embedding router so the ONNX
     * semantic model can be provisioned on demand. When the fallback provider
     * is not a LocalSemanticEmbeddingRouter, this is an honest no-op error
     * (no semantic provisioning path exists in this configuration).
     */
    suspend fun provisionSemanticModel(): Outcome<Unit, String> {
        val router = fallbackEmbeddingProvider as? com.example.infrastructure.memory.semantic.LocalSemanticEmbeddingRouter
            ?: return Outcome.Error("لا يوجد مسار تضمين دلالي محلي في هذا التكوين.")
        return router.provision()
    }

    /**
     * TRUE when the on-device semantic model (ONNX MiniLM) is provisioned and
     * will be used for local semantic retrieval.
     */
    val isLocalSemanticModelReady: Boolean
        get() = (fallbackEmbeddingProvider as? com.example.infrastructure.memory.semantic.LocalSemanticEmbeddingRouter)
            ?.isSemantic ?: false

    private fun bootstrapDefaultKnowledge() {
        val initialDocs = listOf(
            KnowledgeDocument(
                id = "doc_clean_architecture",
                title = "AI-V0 Architectural Blueprint & Domain Rules",
                sourceUri = "workspace://docs/architecture.md",
                content = """
                    # مبادئ معمارية AI-V0 Platform
                    1. المعمارية النظيفة (Clean Architecture): فصل تام بين مجالات Domain و Application و Ports و Infrastructure و Presentation.
                    2. خلو طبقة النطاق من الاعتمادات الخارجية (Pure Kotlin Domain).
                    3. نظام اتخاذ القرار الذاتي CBR-MDP: دمج الذاكرة الإجرائية السابقة مع القيمة المستقبلية للمنفعة.
                    4. عدم استبدال المنطق الحقيقي بأي محاكاة أو أكواد مزيفة.
                    5. دعم كامل لنمط العمل دون اتصال بالإنترنت (Offline First) والنمط الهجين (Intelligent Hybrid).
                """.trimIndent()
            ),
            KnowledgeDocument(
                id = "doc_security_governance",
                title = "Security & Sanitization Guidelines",
                sourceUri = "workspace://docs/security.md",
                content = """
                    # إرشادات الأمان والحوكمة
                    1. حجب وتنقيح المفاتيح السرية (API Keys, Bearer Tokens) قبل الإرسال أو التخزين.
                    2. تأطير مخرجات الأدوات غير الموثوقة داخل علامات <tool_output untrusted="true">.
                    3. عزل مسار الملفات داخل بيئة العمل ومنع ثغرات Path Traversal (../).
                    4. طلب موافقة صريحة للمهام الحساسة وفق سياسة AutonomyPolicy.
                """.trimIndent()
            )
        )
        for (doc in initialDocs) {
            ingestDocumentSync(doc)
        }
    }

    private fun ingestDocumentSync(doc: KnowledgeDocument) {
        val generatedChunks = splitIntoChunks(doc)
        val updatedDoc = doc.copy(totalChunks = generatedChunks.size)
        _documents.update { it + updatedDoc }
        chunks.addAll(generatedChunks)
    }

    /**
     * Ingests a new document into the knowledge base, splits into chunks, and
     * computes embeddings.
     *
     * Per Phase 4: the embedding adapter is resolved via the resource pipeline.
     * The first available ENABLED HEALTHY embedding ResourceRecord is used. If
     * none exists, the `fallbackEmbeddingProvider` (local in-process) is used.
     *
     * Per Section 8: each chunk records which embedding ResourceId generated
     * its vector. This preserves vector-compatibility boundaries across
     * different embedding resources.
     */
    suspend fun ingestDocument(title: String, content: String, sourceUri: String, tags: List<String> = emptyList()): KnowledgeDocument = withContext(Dispatchers.Default) {
        val docId = "doc_${System.currentTimeMillis()}"
        val doc = KnowledgeDocument(
            id = docId, title = title, sourceUri = sourceUri, content = content, tags = tags
        )
        val splitChunks = splitIntoChunks(doc)

        // Resolve the active embedding adapter via the resource pipeline.
        val (embeddingProvider, usedResourceId) = resolveEmbeddingProvider()
        activeEmbeddingResourceId = usedResourceId

        val embeddedChunks = mutableListOf<DocumentChunk>()
        for (chunk in splitChunks) {
            var vector: EmbeddingVector? = null
            if (embeddingProvider != null) {
                val embOutcome = embeddingProvider.generateEmbeddings(listOf(chunk.text))
                if (embOutcome is Outcome.Success) {
                    vector = embOutcome.value.firstOrNull()
                }
            }
            if (vector == null) {
                vector = generateLexicalVector(chunk.text)
            }
            // Provenance (audit 2026 fix): record WHICH embedding source produced
            // the vector so retrieval can enforce the compatibility boundary for
            // real (previously the boundary was claimed but never persisted).
            embeddedChunks.add(
                chunk.copy(
                    vector = vector,
                    metadata = chunk.metadata + mapOf(
                        "embeddingResourceId" to (usedResourceId?.value ?: "local_lexical"),
                        "embeddingSemantic" to isProviderSemantic(embeddingProvider).toString()
                    )
                )
            )
        }

        val completedDoc = doc.copy(totalChunks = embeddedChunks.size)
        _documents.update { it + completedDoc }
        chunks.addAll(embeddedChunks)

        // ------------------------------------------------------------
        // GAP-CLOSURE P1-14 (honest RAG persistence): a failed write is NO
        // LONGER swallowed with a fake "success" (RAM = ingested, DB =
        // missing → knowledge vanished after restart). The write is retried
        // once; on failure the returned document is marked
        // [KnowledgePersistenceState.FAILED] with a diagnostic so the UI and
        // callers know exactly what survived where.
        // ------------------------------------------------------------
        var persistenceState = KnowledgePersistenceState.PERSISTED
        var persistenceDiagnostic: String? = null
        if (persistenceService != null) {
            val targetWorkspace = currentWorkspaceId() ?: workspaceIdProvider()
            val persisted = runCatching {
                persistenceService.persistDocument(
                    workspaceId = targetWorkspace,
                    document = completedDoc,
                    chunks = embeddedChunks
                )
                true
            }
            if (persisted.getOrDefault(false)) {
                persistenceState = KnowledgePersistenceState.PERSISTED
            } else {
                // One honest retry before declaring failure.
                val retried = runCatching {
                    persistenceService.persistDocument(
                        workspaceId = targetWorkspace,
                        document = completedDoc,
                        chunks = embeddedChunks
                    )
                    true
                }
                if (retried.getOrDefault(false)) {
                    persistenceState = KnowledgePersistenceState.PERSISTED
                } else {
                    persistenceState = KnowledgePersistenceState.FAILED
                    persistenceDiagnostic = "RAG_PERSISTENCE_FAILED: أُدرج المستند في الفهرس الحي لكن تعذّر حفظه في قاعدة البيانات (فشلت محاولتان) — سيفقد المستند عند إعادة تشغيل التطبيق: ${persisted.exceptionOrNull()?.localizedMessage ?: retried.exceptionOrNull()?.localizedMessage ?: "سبب غير معروف"}"
                }
            }
        } else {
            persistenceState = KnowledgePersistenceState.PENDING
            persistenceDiagnostic = "لا يوجد مخزن دائم مهيأ — المستند في الذاكرة فقط."
        }

        completedDoc.copy(
            persistenceState = persistenceState,
            persistenceDiagnostic = persistenceDiagnostic
        )
    }

    /**
     * Resolve the active embedding adapter via the resource pipeline.
     *
     * Returns (adapter, resourceId) where:
     *   - adapter: the resolved `EmbeddingProviderPort` (or null if none available)
     *   - resourceId: the `ResourceId` of the resolved adapter (or null for fallback)
     *
     * Per Phase 4: no silent fallback to a hardcoded default. If no embedding
     * ResourceRecord is registered, the `fallbackEmbeddingProvider` is used
     * (which is the local in-process adapter explicitly injected by
     * `AppContainer`). The fallback path is HONEST — the `RetrievalMode` is
     * `LEXICAL_FALLBACK`, not `HYBRID`.
     */
    private suspend fun resolveEmbeddingProvider(): Pair<EmbeddingProviderPort?, ResourceId?> {
        // Find the first ENABLED HEALTHY embedding ResourceRecord.
        val embeddingResources = resourceRegistry.listResources()
            .filter { it.resourceType == ResourceType.EMBEDDING
                && (it.lifecycleState == com.example.domain.core.resource.ResourceLifecycleState.ENABLED
                    || it.lifecycleState == com.example.domain.core.resource.ResourceLifecycleState.ACTIVE)
                && it.runtimeSupported
                && it.healthStatus != HealthStatus.UNAVAILABLE
            }
        // Prefer the one with HEALTHY health status.
        val chosen = embeddingResources.firstOrNull { it.healthStatus == HealthStatus.HEALTHY }
            ?: embeddingResources.firstOrNull()
        if (chosen != null) {
            val resolution = runtimeAdapterResolver.resolveEmbeddingAdapter(chosen.resourceId)
            val adapter = when (resolution) {
                is Outcome.Success -> resolution.value
                is Outcome.Degraded -> resolution.partialValue
                is Outcome.Error -> null
            }
            if (adapter != null) return adapter to chosen.resourceId
        }
        // Fallback to the injected local adapter. This is HONEST — the
        // `RetrievalMode` will be LEXICAL_FALLBACK, not HYBRID.
        return fallbackEmbeddingProvider to null
    }

    private fun splitIntoChunks(doc: KnowledgeDocument, chunkSize: Int = 300, overlap: Int = 50): List<DocumentChunk> {
        val text = doc.content
        val chunkList = mutableListOf<DocumentChunk>()
        var start = 0
        var chunkIndex = 0
        while (start < text.length) {
            val end = (start + chunkSize).coerceAtMost(text.length)
            val chunkText = text.substring(start, end).trim()
            if (chunkText.isNotBlank()) {
                chunkList.add(
                    DocumentChunk(
                        id = "${doc.id}_c$chunkIndex",
                        documentId = doc.id,
                        documentTitle = doc.title,
                        chunkIndex = chunkIndex,
                        text = chunkText,
                        tokenCount = chunkText.length / 4
                    )
                )
                chunkIndex++
            }
            if (end == text.length) break
            start += (chunkSize - overlap).coerceAtLeast(1)
        }
        return chunkList
    }

    /**
     * Semantic and keyword hybrid search over chunked knowledge base.
     *
     * Audit 2026 fixes:
     *  - retrieval mode is HONEST: a hash-based fallback embedding is labeled
     *    LEXICAL_FALLBACK, not HYBRID (previously any non-null provider was
     *    mislabeled HYBRID even when it produced deterministic hash vectors);
     *  - embedding-compatibility boundary is enforced from chunk metadata
     *    (chunks embedded by a different resource are excluded from semantic
     *    scoring and re-scored lexically instead of silently mixed);
     *  - Arabic normalization applied to queries and lexical scoring;
     *  - proper hybrid fusion: normalized semantic + lexical overlap score,
     *    followed by a lexical rerank of the top candidates.
     */
    /**
     * GAP-CLOSURE P2-05: the retrieval-budget parameter is DEPRECATED on
     * this pipeline entry point — the authoritative retrieval-budget
     * authority is the RagIntelligence layer
     * (domain.core.rag.intelligence.RagRequest.maxTokenBudget), and callers
     * should migrate there. Retained for source compatibility only.
     */
    @Deprecated(
        message = "Retrieval budget authority moved to RagIntelligenceService (RagRequest.maxTokenBudget). Use the parameterless budget overload.",
        replaceWith = ReplaceWith("retrieveRelevantContext(query, topK)")
    )
    suspend fun retrieveRelevantContext(query: String, topK: Int = 4, maxTokenBudget: Int = 2000): AssembledRagContext =
        retrieveRelevantContextInternal(query, topK)

    suspend fun retrieveRelevantContext(query: String, topK: Int = 4): AssembledRagContext =
        retrieveRelevantContextInternal(query, topK)

    private suspend fun retrieveRelevantContextInternal(query: String, topK: Int): AssembledRagContext = withContext(Dispatchers.Default) {
        val (embeddingProvider, usedResourceId) = resolveEmbeddingProvider()

        val providerIsSemantic = isProviderSemantic(embeddingProvider)

        val queryVector = if (embeddingProvider != null) {
            val outcome = embeddingProvider.generateEmbeddings(listOf(query))
            if (outcome is Outcome.Success) (outcome.value.firstOrNull() ?: generateLexicalVector(query))
            else generateLexicalVector(query)
        } else {
            generateLexicalVector(query)
        }

        val retrievalMode = when {
            embeddingProvider == null -> RetrievalMode.LEXICAL_FALLBACK
            providerIsSemantic -> RetrievalMode.HYBRID
            else -> RetrievalMode.LEXICAL_FALLBACK // hash fallback — honestly labeled
        }

        val normalizedQuery = com.example.infrastructure.memory.semantic.ArabicTextNormalizer.normalize(query)
        val queryTokens = normalizedQuery.lowercase()
            .split(Regex("[^\\w\\d\\u0600-\\u06FF]+")).filter { it.isNotBlank() }.toSet()

        val scoredChunks = chunks.map { chunk ->
            val chunkEmbeddingId = chunk.metadata["embeddingResourceId"]
            // Compatibility boundary: chunks embedded by a DIFFERENT embedding
            // resource than the active one cannot be compared semantically.
            val vectorCompatible = chunkEmbeddingId == null ||
                usedResourceId == null ||
                chunkEmbeddingId == usedResourceId.value ||
                chunkEmbeddingId == "local_lexical"

            val chunkVector = chunk.vector
                ?: generateLexicalVector(chunk.text).also { /* lazy lexical for legacy chunks */ }

            val sim = if (vectorCompatible) {
                computeCosineSimilarity(queryVector.values, chunkVector.values)
            } else 0.0f

            // Arabic-normalized lexical overlap (token-level F1 score).
            val normalizedChunk = com.example.infrastructure.memory.semantic.ArabicTextNormalizer
                .normalize(chunk.text).lowercase()
            val chunkTokens = normalizedChunk
                .split(Regex("[^\\w\\d\\u0600-\\u06FF]+")).filter { it.isNotBlank() }.toSet()
            val overlap = if (queryTokens.isEmpty() || chunkTokens.isEmpty()) 0.0f
            else {
                val common = queryTokens.intersect(chunkTokens).size.toFloat()
                val precision = common / chunkTokens.size
                val recall = common / queryTokens.size
                if (precision + recall > 0f) 2f * precision * recall / (precision + recall) else 0f
            }

            val semanticWeight = if (vectorCompatible && providerIsSemantic) 0.6f else 0.0f
            val lexicalWeight = 1.0f - semanticWeight
            val combinedScore = (sim * semanticWeight + overlap * lexicalWeight).coerceIn(0.0f, 1.0f)

            RetrievedContextChunk(
                chunk = chunk,
                relevanceScore = combinedScore,
                retrievalMode = retrievalMode,
                snippet = chunk.text
            )
        }
            .filter { it.relevanceScore > 0.05f }
            .sortedByDescending { it.relevanceScore }
            .take(topK * 2)
            // Lexical rerank pass: boost candidates whose text actually
            // contains the (normalized) query tokens verbatim.
            .map { scored ->
                val containsBoost = if (scored.chunk.text.contains(query, ignoreCase = true) ||
                    com.example.infrastructure.memory.semantic.ArabicTextNormalizer
                        .normalize(scored.chunk.text).contains(normalizedQuery, ignoreCase = true)
                ) 0.1f else 0.0f
                scored.copy(relevanceScore = (scored.relevanceScore + containsBoost).coerceAtMost(1.0f))
            }
            .sortedByDescending { it.relevanceScore }
            .take(topK)

        val assembledText = buildString {
            appendLine("=== سياق المعرفة المسترجع (RAG Knowledge Base) ===")
            scoredChunks.forEachIndexed { i, c ->
                appendLine("[مصدر ${i + 1}: ${c.chunk.documentTitle} (صلة: ${"%.2f".format(c.relevanceScore)})]")
                appendLine(c.chunk.text)
                appendLine()
            }
        }

        AssembledRagContext(
            query = query,
            formattedContextText = assembledText,
            retrievedChunks = scoredChunks,
            totalTokensEstimated = assembledText.length / 4,
            isTruncated = false
        )
    }

    /**
     * TRUE only when the embedding provider actually produces semantic
     * vectors (a trained model — e.g. ONNX MiniLM or a cloud embedding API).
     * The deterministic hash fallback is NOT semantic and is labeled as such.
     */
    private fun isProviderSemantic(provider: EmbeddingProviderPort?): Boolean {
        if (provider == null) return false
        return (provider as? com.example.infrastructure.memory.semantic.EmbeddingQualityMarker)?.isSemantic ?: true
    }

    private fun generateLexicalVector(text: String): EmbeddingVector {
        val tokens = text.lowercase().split(Regex("[^\\w\\d]+")).filter { it.isNotBlank() }
        val vector = FloatArray(32) { 0.0f }
        for (token in tokens) {
            val hash = (token.hashCode() and 0x7FFFFFFF) % 32
            vector[hash] += 1.0f
        }
        val norm = sqrt(vector.sumOf { (it * it).toDouble() }).toFloat()
        if (norm > 0.001f) {
            for (i in vector.indices) vector[i] /= norm
        }
        return EmbeddingVector(vector)
    }

    private fun computeCosineSimilarity(vecA: FloatArray, vecB: FloatArray): Float {
        val len = minOf(vecA.size, vecB.size)
        if (len == 0) return 0.0f
        var dot = 0.0f
        var nA = 0.0f
        var nB = 0.0f
        for (i in 0 until len) {
            dot += vecA[i] * vecB[i]
            nA += vecA[i] * vecA[i]
            nB += vecB[i] * vecB[i]
        }
        val denom = (sqrt(nA.toDouble()) * sqrt(nB.toDouble())).toFloat()
        return if (denom > 1e-6f) (dot / denom).coerceIn(-1.0f, 1.0f) else 0.0f
    }
}
