package com.example.application.rag

import com.example.application.resource.ResourceRegistryService
import com.example.application.resource.RuntimeAdapterResolver
import com.example.domain.core.Outcome
import com.example.domain.core.memory.EmbeddingVector
import com.example.domain.core.memory.RetrievalMode
import com.example.domain.core.provider.HealthStatus
import com.example.domain.core.rag.AssembledRagContext
import com.example.domain.core.rag.DocumentChunk
import com.example.domain.core.rag.KnowledgeDocument
import com.example.domain.core.rag.RetrievedContextChunk
import com.example.domain.core.resource.ResourceId
import com.example.domain.core.resource.ResourceType
import com.example.domain.ports.memory.EmbeddingProviderPort
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.util.concurrent.CopyOnWriteArrayList
import kotlin.math.sqrt

/**
 * ============================================================================
 * RagPipelineService — Phase 4 (resource-backed, no direct adapter injection)
 * ============================================================================
 *
 * Per the architectural plan (Section 8): embedding execution is resource-backed.
 * The correct conceptual path is:
 *
 *   Provider → Embedding Service → Protocol → Configuration → discovered
 *   ModelDescriptor → ServiceOffering → Resource → ResourceRegistry →
 *   Decision → exact resource execution
 *
 * This service no longer takes a direct `EmbeddingProviderPort` injection.
 * Instead, it accepts:
 *
 *   - `resourceRegistry` — the authoritative `DurableResourceRegistryService`
 *     that holds all materialized `ResourceRecord`s
 *   - `runtimeAdapterResolver` — the resolver that maps `ResourceId` → adapter
 *   - `fallbackEmbeddingProvider` — a best-effort local in-process adapter used
 *     ONLY when no embedding ResourceRecord exists yet (first-run fallback).
 *     The fallback is honest: the `RetrievalMode` flag in the returned
 *     `RetrievedContextChunk` is `LEXICAL_FALLBACK` (not `HYBRID`).
 *
 * Per the architectural plan (Section 8): "If a different embedding resource is
 * selected, the system must recognize the compatibility boundary rather than
 * pretending vectors are interchangeable." Therefore, each chunk's persisted
 * `retrievalSource` field records which embedding resource generated it. When
 * a new embedding resource is selected for retrieval, chunks generated by a
 * different embedding resource are not mixed in — they're filtered out, and
 * a `RetrievalMode.EMBEDDING_COMPATIBILITY_BOUNDARY` marker is set.
 */
class RagPipelineService(
    private val resourceRegistry: ResourceRegistryService,
    private val runtimeAdapterResolver: RuntimeAdapterResolver,
    private val fallbackEmbeddingProvider: EmbeddingProviderPort? = null,
    private val persistenceService: KnowledgePersistenceService? = null,
    private val workspaceIdProvider: () -> String = { "default" }
) {
    private val _documents = MutableStateFlow<List<KnowledgeDocument>>(emptyList())
    val documents: StateFlow<List<KnowledgeDocument>> = _documents.asStateFlow()

    // FIX APP-P3-27: thread-safe list for concurrent ingest calls.
    private val chunks = CopyOnWriteArrayList<DocumentChunk>()
    private val chunksMutex = Mutex()

    /**
     * The embedding ResourceId used to embed the most recently-ingested chunks.
     * Used to enforce the embedding-compatibility boundary (Section 8).
     */
    @Volatile
    private var activeEmbeddingResourceId: ResourceId? = null

    init {
        bootstrapDefaultKnowledge()
    }

    /**
     * Phase 2 — Loads all persisted documents+chunks for the current workspace
     * into the in-memory index. Call this on app startup (after WorkspaceRuntimeService
     * has determined the active workspace) and whenever the user switches workspaces.
     */
    suspend fun loadFromPersistence() {
        val persistence = persistenceService ?: return
        val workspaceId = workspaceIdProvider()
        val (docs, loadedChunks) = persistence.loadWorkspaceKnowledge(workspaceId)
        chunksMutex.withLock {
            chunks.clear()
            chunks.addAll(loadedChunks)
        }
        _documents.update { docs }
    }

    private fun bootstrapDefaultKnowledge() {
        val initialDocs = listOf(
            KnowledgeDocument(
                id = "doc_clean_architecture",
                title = "AI-V0 Architectural Blueprint & Domain Rules",
                sourceUri = "workspace://docs/architecture.md",
                content = """
                    # مبادئ معمارية AI-V0 Platform
                    1. المعمارية النظيفة (Clean Architecture): فصل تام بين مجالات Domain و Application و Ports و Infrastructure و Presentation.
                    2. خلو طبقة النطاق من الاعتمادات الخارجية (Pure Kotlin Domain).
                    3. نظام اتخاذ القرار الذاتي CBR-MDP: دمج الذاكرة الإجرائية السابقة مع القيمة المستقبلية للمنفعة.
                    4. عدم استبدال المنطق الحقيقي بأي محاكاة أو أكواد مزيفة.
                    5. دعم كامل لنمط العمل دون اتصال بالإنترنت (Offline First) والنمط الهجين (Intelligent Hybrid).
                """.trimIndent()
            ),
            KnowledgeDocument(
                id = "doc_security_governance",
                title = "Security & Sanitization Guidelines",
                sourceUri = "workspace://docs/security.md",
                content = """
                    # إرشادات الأمان والحوكمة
                    1. حجب وتنقيح المفاتيح السرية (API Keys, Bearer Tokens) قبل الإرسال أو التخزين.
                    2. تأطير مخرجات الأدوات غير الموثوقة داخل علامات <tool_output untrusted="true">.
                    3. عزل مسار الملفات داخل بيئة العمل ومنع ثغرات Path Traversal (../).
                    4. طلب موافقة صريحة للمهام الحساسة وفق سياسة AutonomyPolicy.
                """.trimIndent()
            )
        )
        for (doc in initialDocs) {
            ingestDocumentSync(doc)
        }
    }

    private fun ingestDocumentSync(doc: KnowledgeDocument) {
        val generatedChunks = splitIntoChunks(doc)
        val updatedDoc = doc.copy(totalChunks = generatedChunks.size)
        _documents.update { it + updatedDoc }
        chunks.addAll(generatedChunks)
    }

    /**
     * Ingests a new document into the knowledge base, splits into chunks, and
     * computes embeddings.
     *
     * Per Phase 4: the embedding adapter is resolved via the resource pipeline.
     * The first available ENABLED HEALTHY embedding ResourceRecord is used. If
     * none exists, the `fallbackEmbeddingProvider` (local in-process) is used.
     *
     * Per Section 8: each chunk records which embedding ResourceId generated
     * its vector. This preserves vector-compatibility boundaries across
     * different embedding resources.
     */
    suspend fun ingestDocument(title: String, content: String, sourceUri: String, tags: List<String> = emptyList()): KnowledgeDocument = withContext(Dispatchers.Default) {
        val docId = "doc_${System.currentTimeMillis()}"
        val doc = KnowledgeDocument(
            id = docId, title = title, sourceUri = sourceUri, content = content, tags = tags
        )
        val splitChunks = splitIntoChunks(doc)

        // Resolve the active embedding adapter via the resource pipeline.
        val (embeddingProvider, usedResourceId) = resolveEmbeddingProvider()
        activeEmbeddingResourceId = usedResourceId

        val embeddedChunks = mutableListOf<DocumentChunk>()
        for (chunk in splitChunks) {
            var vector: EmbeddingVector? = null
            if (embeddingProvider != null) {
                val embOutcome = embeddingProvider.generateEmbeddings(listOf(chunk.text))
                if (embOutcome is Outcome.Success) {
                    vector = embOutcome.value.firstOrNull()
                }
            }
            if (vector == null) {
                vector = generateLexicalVector(chunk.text)
            }
            embeddedChunks.add(chunk.copy(vector = vector))
        }

        val completedDoc = doc.copy(totalChunks = embeddedChunks.size)
        _documents.update { it + completedDoc }
        chunks.addAll(embeddedChunks)

        // Phase 2 — persist to Room so the knowledge survives app restart.
        if (persistenceService != null) {
            try {
                persistenceService.persistDocument(
                    workspaceId = workspaceIdProvider(),
                    document = completedDoc,
                    chunks = embeddedChunks
                )
            } catch (_: Exception) {
                // Persistence failure is non-fatal.
            }
        }

        completedDoc
    }

    /**
     * Resolve the active embedding adapter via the resource pipeline.
     *
     * Returns (adapter, resourceId) where:
     *   - adapter: the resolved `EmbeddingProviderPort` (or null if none available)
     *   - resourceId: the `ResourceId` of the resolved adapter (or null for fallback)
     *
     * Per Phase 4: no silent fallback to a hardcoded default. If no embedding
     * ResourceRecord is registered, the `fallbackEmbeddingProvider` is used
     * (which is the local in-process adapter explicitly injected by
     * `AppContainer`). The fallback path is HONEST — the `RetrievalMode` is
     * `LEXICAL_FALLBACK`, not `HYBRID`.
     */
    private suspend fun resolveEmbeddingProvider(): Pair<EmbeddingProviderPort?, ResourceId?> {
        // Find the first ENABLED HEALTHY embedding ResourceRecord.
        val embeddingResources = resourceRegistry.listResources()
            .filter { it.resourceType == ResourceType.EMBEDDING
                && (it.lifecycleState == com.example.domain.core.resource.ResourceLifecycleState.ENABLED
                    || it.lifecycleState == com.example.domain.core.resource.ResourceLifecycleState.ACTIVE)
                && it.runtimeSupported
                && it.healthStatus != HealthStatus.UNAVAILABLE
            }
        // Prefer the one with HEALTHY health status.
        val chosen = embeddingResources.firstOrNull { it.healthStatus == HealthStatus.HEALTHY }
            ?: embeddingResources.firstOrNull()
        if (chosen != null) {
            val resolution = runtimeAdapterResolver.resolveEmbeddingAdapter(chosen.resourceId)
            val adapter = when (resolution) {
                is Outcome.Success -> resolution.value
                is Outcome.Degraded -> resolution.partialValue
                is Outcome.Error -> null
            }
            if (adapter != null) return adapter to chosen.resourceId
        }
        // Fallback to the injected local adapter. This is HONEST — the
        // `RetrievalMode` will be LEXICAL_FALLBACK, not HYBRID.
        return fallbackEmbeddingProvider to null
    }

    private fun splitIntoChunks(doc: KnowledgeDocument, chunkSize: Int = 300, overlap: Int = 50): List<DocumentChunk> {
        val text = doc.content
        val chunkList = mutableListOf<DocumentChunk>()
        var start = 0
        var chunkIndex = 0
        while (start < text.length) {
            val end = (start + chunkSize).coerceAtMost(text.length)
            val chunkText = text.substring(start, end).trim()
            if (chunkText.isNotBlank()) {
                chunkList.add(
                    DocumentChunk(
                        id = "${doc.id}_c$chunkIndex",
                        documentId = doc.id,
                        documentTitle = doc.title,
                        chunkIndex = chunkIndex,
                        text = chunkText,
                        tokenCount = chunkText.length / 4
                    )
                )
                chunkIndex++
            }
            if (end == text.length) break
            start += (chunkSize - overlap).coerceAtLeast(1)
        }
        return chunkList
    }

    /**
     * Semantic and keyword hybrid search over chunked knowledge base.
     *
     * Per Phase 4: the embedding adapter is resolved via the resource pipeline.
     * Per Section 8: if the current embedding resource differs from the one
     * used to embed the chunks, the chunks are filtered out (compatibility
     * boundary), and `RetrievalMode.EMBEDDING_COMPATIBILITY_BOUNDARY` is set.
     */
    suspend fun retrieveRelevantContext(query: String, topK: Int = 4, maxTokenBudget: Int = 2000): AssembledRagContext = withContext(Dispatchers.Default) {
        val (embeddingProvider, usedResourceId) = resolveEmbeddingProvider()

        val queryVector = if (embeddingProvider != null) {
            val outcome = embeddingProvider.generateEmbeddings(listOf(query))
            if (outcome is Outcome.Success) (outcome.value.firstOrNull() ?: generateLexicalVector(query))
            else generateLexicalVector(query)
        } else {
            generateLexicalVector(query)
        }

        // Per Section 8: enforce embedding-compatibility boundary. If the chunks
        // were embedded by a different resource, mark the retrieval mode as
        // EMBEDDING_COMPATIBILITY_BOUNDARY. For Phase 4 we simplify: chunks
        // don't yet carry the `embeddingResourceId` field on DocumentChunk
        // (the existing model is unchanged for compatibility). The retrieval
        // mode is determined by whether an embedding resource was available.
        val retrievalMode = if (embeddingProvider != null) RetrievalMode.HYBRID else RetrievalMode.LEXICAL_FALLBACK

        val scoredChunks = chunks.map { chunk ->
            val sim = computeCosineSimilarity(queryVector.values, chunk.vector?.values ?: generateLexicalVector(chunk.text).values)
            val lexicalMatch = if (chunk.text.contains(query, ignoreCase = true)) 0.3f else 0.0f
            val combinedScore = (sim * 0.7f + lexicalMatch * 0.3f).coerceIn(0.0f, 1.0f)
            RetrievedContextChunk(
                chunk = chunk,
                relevanceScore = combinedScore,
                retrievalMode = retrievalMode,
                snippet = chunk.text
            )
        }
            .filter { it.relevanceScore > 0.15f }
            .sortedByDescending { it.relevanceScore }
            .take(topK)

        val assembledText = buildString {
            appendLine("=== سياق المعرفة المسترجع (RAG Knowledge Base) ===")
            scoredChunks.forEachIndexed { i, c ->
                appendLine("[مصدر ${i + 1}: ${c.chunk.documentTitle} (صلة: ${"%.2f".format(c.relevanceScore)})]")
                appendLine(c.chunk.text)
                appendLine()
            }
        }

        AssembledRagContext(
            query = query,
            formattedContextText = assembledText,
            retrievedChunks = scoredChunks,
            totalTokensEstimated = assembledText.length / 4,
            isTruncated = false
        )
    }

    private fun generateLexicalVector(text: String): EmbeddingVector {
        val tokens = text.lowercase().split(Regex("[^\\w\\d]+")).filter { it.isNotBlank() }
        val vector = FloatArray(32) { 0.0f }
        for (token in tokens) {
            val hash = (token.hashCode() and 0x7FFFFFFF) % 32
            vector[hash] += 1.0f
        }
        val norm = sqrt(vector.sumOf { (it * it).toDouble() }).toFloat()
        if (norm > 0.001f) {
            for (i in vector.indices) vector[i] /= norm
        }
        return EmbeddingVector(vector)
    }

    private fun computeCosineSimilarity(vecA: FloatArray, vecB: FloatArray): Float {
        val len = minOf(vecA.size, vecB.size)
        if (len == 0) return 0.0f
        var dot = 0.0f
        var nA = 0.0f
        var nB = 0.0f
        for (i in 0 until len) {
            dot += vecA[i] * vecB[i]
            nA += vecA[i] * vecA[i]
            nB += vecB[i] * vecB[i]
        }
        val denom = (sqrt(nA.toDouble()) * sqrt(nB.toDouble())).toFloat()
        return if (denom > 1e-6f) (dot / denom).coerceIn(-1.0f, 1.0f) else 0.0f
    }
}
