package com.example.application.rag

import com.example.application.resource.ResourceRegistryService
import com.example.application.resource.RuntimeAdapterResolver
import com.example.domain.core.Outcome
import com.example.domain.core.execution.ExecutionScope
import com.example.domain.core.memory.EmbeddingVector
import com.example.domain.core.memory.RetrievalMode
import com.example.domain.core.provider.HealthStatus
import com.example.domain.core.rag.AssembledRagContext
import com.example.domain.core.rag.DocumentChunk
import com.example.domain.core.rag.KnowledgeDocument
import com.example.domain.core.rag.RetrievalScopeMode
import com.example.domain.core.rag.KnowledgePersistenceState
import com.example.domain.core.rag.RetrievedContextChunk
import com.example.domain.core.resource.ResourceId
import com.example.domain.core.resource.ResourceType
import com.example.domain.ports.memory.EmbeddingProviderPort
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.util.concurrent.CopyOnWriteArrayList
import java.util.concurrent.atomic.AtomicLong
import kotlin.math.sqrt

/**
 * ============================================================================
 * RagPipelineService — Phase 4 (resource-backed, no direct adapter injection)
 * ============================================================================
 *
 * Per the architectural plan (Section 8): embedding execution is resource-backed.
 * The correct conceptual path is:
 *
 *   Provider → Embedding Service → Protocol → Configuration → discovered
 *   ModelDescriptor → ServiceOffering → Resource → ResourceRegistry →
 *   Decision → exact resource execution
 *
 * This service no longer takes a direct `EmbeddingProviderPort` injection.
 * Instead, it accepts:
 *
 *   - `resourceRegistry` — the authoritative `DurableResourceRegistryService`
 *     that holds all materialized `ResourceRecord`s
 *   - `runtimeAdapterResolver` — the resolver that maps `ResourceId` → adapter
 *   - `fallbackEmbeddingProvider` — a best-effort local in-process adapter used
 *     ONLY when no embedding ResourceRecord exists yet (first-run fallback).
 *     The fallback is honest: the `RetrievalMode` flag in the returned
 *     `RetrievedContextChunk` is `LEXICAL_FALLBACK` (not `HYBRID`).
 *
 * Per the architectural plan (Section 8): "If a different embedding resource is
 * selected, the system must recognize the compatibility boundary rather than
 * pretending vectors are interchangeable." Therefore, each chunk's persisted
 * `retrievalSource` field records which embedding resource generated it. When
 * a new embedding resource is selected for retrieval, chunks generated by a
 * different embedding resource are not mixed in — they're filtered out, and
 * a `RetrievalMode.EMBEDDING_COMPATIBILITY_BOUNDARY` marker is set.
 */
class RagPipelineService(
    private val resourceRegistry: ResourceRegistryService,
    private val runtimeAdapterResolver: RuntimeAdapterResolver,
    private val fallbackEmbeddingProvider: EmbeddingProviderPort? = null,
    private val persistenceService: KnowledgePersistenceService? = null,
    private val workspaceIdProvider: () -> String = { "default" },
    /**
     * Audit 2026 (§29 — workspace knowledge has NO size limit): bounded
     * corpus. Ingesting beyond [maxDocumentsPerWorkspace] /
     * [maxChunksPerWorkspace] evicts the OLDEST documents (insertion order)
     * and reports every eviction in the observable [corpusEvictions] flow —
     * the corpus degrades HONESTLY instead of growing without bound in RAM.
     */
    private val maxDocumentsPerWorkspace: Int = 256,
    private val maxChunksPerWorkspace: Int = 24_000
) {
    private val _documents = MutableStateFlow<List<KnowledgeDocument>>(emptyList())
    val documents: StateFlow<List<KnowledgeDocument>> = _documents.asStateFlow()

    // FIX APP-P3-27: thread-safe list for concurrent ingest calls.
    private val chunks = CopyOnWriteArrayList<DocumentChunk>()
    private val chunksMutex = Mutex()

    /**
     * P1-5 (audit 2026 §29 — RAG full-scan architecture): the retrieval
     * index. Normalized text + precomputed token set per chunk — the
     * legacy path re-normalized and re-tokenized the ENTIRE corpus on EVERY
     * query, which is what actually degraded with knowledge growth (not the
     * cosine dot products, which are cheap).
     */
    private data class IndexedChunk(
        val chunk: DocumentChunk,
        val normalizedLower: String,
        val tokens: Set<String>
    )

    private val indexedChunks = CopyOnWriteArrayList<IndexedChunk>()

    /** P1-5: honest bound on the per-query scan (degrades instead of stalling). */
    private val maxScanChunks = 8_000

    /**
     * Audit 2026 (§29 — no workspace-knowledge size limit): the LAST
     * [EVICTION_LOG_WINDOW] corpus evictions, observable. Non-empty means
     * the workspace corpus is at its bound and the OLDEST knowledge was
     * dropped — an honest degradation signal, never silent loss.
     */
    private val _corpusEvictions = MutableStateFlow<List<String>>(emptyList())
    val corpusEvictions: StateFlow<List<String>> = _corpusEvictions.asStateFlow()

    private fun recordEviction(entry: String) {
        _corpusEvictions.value = (listOf(entry) + _corpusEvictions.value).take(EVICTION_LOG_WINDOW)
    }

    private companion object {
        const val EVICTION_LOG_WINDOW = 64
    }

    /**
     * Audit 2026 (§29): enforce the corpus bounds — evict the OLDEST
     * documents (and all their chunks + index entries) while the corpus is
     * over [maxDocumentsPerWorkspace] or [maxChunksPerWorkspace]. Every
     * eviction is recorded in [corpusEvictions] (honest, observable).
     */
    private fun enforceCorpusBounds() {
        var evictedDocs = 0
        var evictedChunks = 0
        // 1) Total-chunk bound (evict oldest documents until under it).
        while (chunks.size > maxChunksPerWorkspace && _documents.value.isNotEmpty()) {
            val victim = _documents.value.first()
            evictedDocs++
            evictedChunks += chunks.count { it.documentId == victim.id }
            removeDocumentWorkingSet(victim.id)
        }
        // 2) Document-count bound.
        while (_documents.value.size > maxDocumentsPerWorkspace) {
            val victim = _documents.value.first()
            evictedDocs++
            evictedChunks += chunks.count { it.documentId == victim.id }
            removeDocumentWorkingSet(victim.id)
        }
        if (evictedDocs > 0) {
            recordEviction(
                "CORPUS_BOUND(RAM): evicted $evictedDocs document(s) / $evictedChunks chunk(s) " +
                    "from the IN-MEMORY working set (limits: docs=$maxDocumentsPerWorkspace, " +
                    "chunks=$maxChunksPerWorkspace). Persistent knowledge is RETAINED — " +
                    "this is a memory-pressure eviction, NOT a deletion."
            )
        }
    }

    /** Removes a document's RAM working set (document row, chunks, index). */
    private fun removeDocumentWorkingSet(documentId: String) {
        _documents.update { docs -> docs.filterNot { it.id == documentId } }
        // NOTE: CopyOnWriteArrayList iterators do NOT support remove() — the
        // Kotlin removeAll(predicate) extension would throw. removeIf is the
        // COW-safe atomic removal.
        chunks.removeIf { it.documentId == documentId }
        indexedChunks.removeIf { it.chunk.documentId == documentId }
        // REPAIR ORDER §15 — keep the scope index consistent with the working set.
        docProjectIndex = docProjectIndex - documentId
    }

    private fun indexChunk(chunk: DocumentChunk): IndexedChunk {
        val normalizedLower = com.example.infrastructure.memory.semantic.ArabicTextNormalizer
            .normalize(chunk.text).lowercase()
        val tokens = normalizedLower
            .split(Regex("[^\\w\\d\\u0600-\\u06FF]+")).filter { it.isNotBlank() }.toSet()
        return IndexedChunk(chunk, normalizedLower, tokens)
    }

    private fun reindexAll() {
        indexedChunks.clear()
        chunks.forEach { indexedChunks.add(indexChunk(it)) }
    }

    /**
     * GAP-CLOSURE P1-15 (stale async load guard): monotonic generation
     * counter for workspace knowledge loads. A load started for workspace A
     * that finishes AFTER a newer load for workspace B is DISCARDED — the
     * working set can never be overwritten by stale async results.
     */
    private val loadGeneration = AtomicLong(0)

    /**
     * GAP-CLOSURE P0-02: resolves the workspace for THIS call — the
     * execution-pinned scope when running inside an agent execution, else
     * the active-workspace provider (user-driven calls).
     */
    private suspend fun currentWorkspaceId(): String? {
        val pinned = currentCoroutineContext()[ExecutionScope.Key]?.workspaceId
        if (pinned != null) return pinned
        return runCatching { workspaceIdProvider() }.getOrNull()
    }

    /**
     * The embedding ResourceId used to embed the most recently-ingested chunks.
     * Used to enforce the embedding-compatibility boundary (Section 8).
     */
    @Volatile
    private var activeEmbeddingResourceId: ResourceId? = null

    /** Audit 2026: collision-free document id generator (see ingestDocument). */
    private val docIdCounter = AtomicLong(0)

    /**
     * REPAIR ORDER §15 — the workspace whose knowledge is CURRENTLY in the
     * RAM working set. Retrieval checks this and RELOADS when the pinned
     * scope's workspace differs (previously retrieval scanned whatever was
     * last loaded — a mid-execution workspace switch silently returned the
     * OTHER workspace's knowledge).
     */
    @Volatile
    private var loadedWorkspaceId: String? = null

    /** REPAIR ORDER §15 — documentId → projectId (for scope-mode filtering). */
    @Volatile
    private var docProjectIndex: Map<String, Long?> = emptyMap()

    private fun rebuildDocProjectIndex() {
        docProjectIndex = _documents.value.associate { it.id to it.projectId }
    }

    /**
     * REPAIR ORDER §15 — resolves the retrieval scope: the pinned
     * ExecutionScope (agent executions) else the active workspace, and
     * RELOADS the working set when it does not match. Returns null when no
     * scope can be resolved (honest empty retrieval — fail-closed).
     */
    private suspend fun ensureWorkingSetForPinnedScope(): Pair<String, Long?>? {
        val pinnedScope = currentCoroutineContext()[ExecutionScope.Key]
        val workspaceId = pinnedScope?.workspaceId ?: runCatching { workspaceIdProvider() }.getOrNull()
            ?: return null
        if (loadedWorkspaceId != workspaceId && persistenceService != null) {
            // Stale working set (workspace switch mid-execution): reload for
            // the PINNED workspace — the scope the caller actually runs in.
            loadFromPersistence()
        }
        return workspaceId to pinnedScope?.projectId?.takeIf { it > 0 }
    }

    init {
        bootstrapDefaultKnowledge()
    }

    /**
     * Phase 2 — Loads all persisted documents+chunks for the current workspace
     * into the in-memory index. Call this on app startup (after WorkspaceRuntimeService
     * has determined the active workspace) and whenever the user switches workspaces.
     *
     * GAP-CLOSURE P1-15: the load is generation-guarded — if a NEWER load
     * (another workspace switch) started while this one was reading, this
     * result is discarded instead of clobbering the newer workspace's
     * working set (the A-load / B-load / A-finishes-last race).
     *
     * REPAIR ORDER §15 — (a) the loaded scope is TRACKED ([loadedWorkspaceId])
     * so retrieval can detect and repair a stale working set instead of
     * returning ANOTHER workspace's knowledge; (b) corpus bounds are
     * enforced AFTER load (previously an over-bound corpus was fully
     * resurrected on every restart and then re-evicted piecemeal on the
     * next ingest — a thrash loop); (c) [projectId] scopes the load to a
     * project view (project-private + workspace-shared).
     */
    suspend fun loadFromPersistence(projectId: Long? = null) {
        val persistence = persistenceService ?: return
        val generation = loadGeneration.incrementAndGet()
        val workspaceId = workspaceIdProvider()
        val (docs, loadedChunks) = persistence.loadWorkspaceKnowledge(workspaceId, projectId)
        // Stale-result guard: only the LATEST load may mutate the index.
        if (loadGeneration.get() != generation) return
        chunksMutex.withLock {
            chunks.clear()
            chunks.addAll(loadedChunks)
            reindexAll()
        }
        _documents.update { docs }
        rebuildDocProjectIndex()
        loadedWorkspaceId = workspaceId
        // REPAIR ORDER §15 — enforce the SAME bounds after load (eviction is
        // RAM-only and honestly labeled: persistent knowledge is RETAINED).
        enforceCorpusBounds()
    }

    /**
     * Deletes a document from the knowledge base: removes it (and its chunks)
     * from the in-memory index AND deletes it durably from Room. Honest
     * outcome — when no durable store is wired the deletion is reported as
     * volatile-only instead of pretending persistence.
     */
    suspend fun deleteDocument(documentId: String): Outcome<Unit, String> {
        // 1. Durable deletion (Room) — the authoritative store.
        val durableDelete: Boolean = persistenceService?.let { persistence ->
            runCatching { persistence.deleteDocument(documentId) }.isSuccess
        } ?: false

        // 2. In-memory index removal (documents flow + chunk index).
        _documents.update { docs -> docs.filterNot { it.id == documentId } }
        chunksMutex.withLock {
            // COW-safe removal (CopyOnWriteArrayList iterators do NOT support
            // remove() — the removeAll(predicate) extension would throw).
            chunks.removeIf { it.documentId == documentId }
            indexedChunks.removeIf { it.chunk.documentId == documentId }
        }

        return when {
            persistenceService == null -> Outcome.Error(
                "لا يوجد مخزن دائم للمعرفة في هذا التكوين — الحذف كان في الذاكرة فقط."
            )
            durableDelete -> Outcome.Success(Unit)
            else -> Outcome.Error("تعذر حذف المستند من المخزن الدائم (راجع سجل الأخطاء).")
        }
    }

    /**
     * Audit 2026 fix: delegates to the local embedding router so the ONNX
     * semantic model can be provisioned on demand. When the fallback provider
     * is not a LocalSemanticEmbeddingRouter, this is an honest no-op error
     * (no semantic provisioning path exists in this configuration).
     */
    suspend fun provisionSemanticModel(): Outcome<Unit, String> {
        val router = fallbackEmbeddingProvider as? com.example.infrastructure.memory.semantic.LocalSemanticEmbeddingRouter
            ?: return Outcome.Error("لا يوجد مسار تضمين دلالي محلي في هذا التكوين.")
        return router.provision()
    }

    /**
     * TRUE when the on-device semantic model (ONNX MiniLM) is provisioned and
     * will be used for local semantic retrieval.
     */
    val isLocalSemanticModelReady: Boolean
        get() = (fallbackEmbeddingProvider as? com.example.infrastructure.memory.semantic.LocalSemanticEmbeddingRouter)
            ?.isSemantic ?: false

    private fun bootstrapDefaultKnowledge() {
        val initialDocs = listOf(
            KnowledgeDocument(
                id = "doc_clean_architecture",
                title = "AI-V0 Architectural Blueprint & Domain Rules",
                sourceUri = "workspace://docs/architecture.md",
                content = """
                    # مبادئ معمارية AI-V0 Platform
                    1. المعمارية النظيفة (Clean Architecture): فصل تام بين مجالات Domain و Application و Ports و Infrastructure و Presentation.
                    2. خلو طبقة النطاق من الاعتمادات الخارجية (Pure Kotlin Domain).
                    3. نظام اتخاذ القرار الذاتي CBR-MDP: دمج الذاكرة الإجرائية السابقة مع القيمة المستقبلية للمنفعة.
                    4. عدم استبدال المنطق الحقيقي بأي محاكاة أو أكواد مزيفة.
                    5. دعم كامل لنمط العمل دون اتصال بالإنترنت (Offline First) والنمط الهجين (Intelligent Hybrid).
                """.trimIndent()
            ),
            KnowledgeDocument(
                id = "doc_security_governance",
                title = "Security & Sanitization Guidelines",
                sourceUri = "workspace://docs/security.md",
                content = """
                    # إرشادات الأمان والحوكمة
                    1. حجب وتنقيح المفاتيح السرية (API Keys, Bearer Tokens) قبل الإرسال أو التخزين.
                    2. تأطير مخرجات الأدوات غير الموثوقة داخل علامات <tool_output untrusted="true">.
                    3. عزل مسار الملفات داخل بيئة العمل ومنع ثغرات Path Traversal (../).
                    4. طلب موافقة صريحة للمهام الحساسة وفق سياسة AutonomyPolicy.
                """.trimIndent()
            )
        )
        for (doc in initialDocs) {
            ingestDocumentSync(doc)
        }
    }

    private fun ingestDocumentSync(doc: KnowledgeDocument) {
        val generatedChunks = splitIntoChunks(doc)
        val updatedDoc = doc.copy(totalChunks = generatedChunks.size)
        _documents.update { it + updatedDoc }
        chunks.addAll(generatedChunks)
        // P1-5: keep the retrieval index in sync with ingested chunks.
        generatedChunks.forEach { indexedChunks.add(indexChunk(it)) }
        // Audit 2026 (§29): bounded corpus — evict oldest when over the limits.
        enforceCorpusBounds()
    }

    /**
     * Ingests a new document into the knowledge base, splits into chunks, and
     * computes embeddings.
     *
     * Per Phase 4: the embedding adapter is resolved via the resource pipeline.
     * The first available ENABLED HEALTHY embedding ResourceRecord is used. If
     * none exists, the `fallbackEmbeddingProvider` (local in-process) is used.
     *
     * Per Section 8: each chunk records which embedding ResourceId generated
     * its vector. This preserves vector-compatibility boundaries across
     * different embedding resources.
     *
     * REPAIR ORDER §15: [projectId] scopes the ingested knowledge — null
     * (default) = WORKSPACE-SHARED, non-null = PROJECT-PRIVATE.
     */
    suspend fun ingestDocument(
        title: String,
        content: String,
        sourceUri: String,
        tags: List<String> = emptyList(),
        projectId: Long? = null
    ): KnowledgeDocument = withContext(Dispatchers.Default) {
        // Audit 2026: collision-free document id. A timestamp-only id made
        // two documents ingested within the same millisecond THE SAME
        // document (eviction/deletion then wiped them all at once).
        val docId = "doc_${System.currentTimeMillis()}_${docIdCounter.incrementAndGet()}"
        val doc = KnowledgeDocument(
            id = docId, title = title, sourceUri = sourceUri, content = content, tags = tags,
            projectId = projectId
        )
        val splitChunks = splitIntoChunks(doc)

        // Resolve the active embedding adapter via the resource pipeline.
        val (embeddingProvider, usedResourceId) = resolveEmbeddingProvider()
        activeEmbeddingResourceId = usedResourceId

        // P1-5 (audit 2026 §29 — ingestion embedding was NOT batched): ONE
        // batched embedding call for the whole document's chunks instead of
        // a provider round-trip per chunk (N provider calls → 1).
        val batchVectors: List<EmbeddingVector>? = if (embeddingProvider != null) {
            when (val batchOutcome = embeddingProvider.generateEmbeddings(splitChunks.map { it.text })) {
                is Outcome.Success -> batchOutcome.value
                else -> null
            }
        } else null

        val embeddedChunks = mutableListOf<DocumentChunk>()
        for ((index, chunk) in splitChunks.withIndex()) {
            var vector: EmbeddingVector? = batchVectors?.getOrNull(index)
            if (vector == null) {
                vector = generateLexicalVector(chunk.text)
            }
            // Provenance (audit 2026 fix): record WHICH embedding source produced
            // the vector so retrieval can enforce the compatibility boundary for
            // real (previously the boundary was claimed but never persisted).
            embeddedChunks.add(
                chunk.copy(
                    vector = vector,
                    metadata = chunk.metadata + mapOf(
                        "embeddingResourceId" to (usedResourceId?.value ?: "local_lexical"),
                        "embeddingSemantic" to isProviderSemantic(embeddingProvider).toString()
                    )
                )
            )
        }

        val completedDoc = doc.copy(totalChunks = embeddedChunks.size)
        _documents.update { it + completedDoc }
        chunks.addAll(embeddedChunks)
        // P1-5: keep the retrieval index in sync with ingested chunks.
        embeddedChunks.forEach { indexedChunks.add(indexChunk(it)) }
        rebuildDocProjectIndex()
        // Audit 2026 (§29): bounded corpus — evict oldest when over the limits.
        enforceCorpusBounds()

        // ------------------------------------------------------------
        // GAP-CLOSURE P1-14 (honest RAG persistence): a failed write is NO
        // LONGER swallowed with a fake "success" (RAM = ingested, DB =
        // missing → knowledge vanished after restart). The write is retried
        // once; on failure the returned document is marked
        // [KnowledgePersistenceState.FAILED] with a diagnostic so the UI and
        // callers know exactly what survived where.
        // ------------------------------------------------------------
        var persistenceState = KnowledgePersistenceState.PERSISTED
        var persistenceDiagnostic: String? = null
        if (persistenceService != null) {
            val targetWorkspace = currentWorkspaceId() ?: workspaceIdProvider()
            val persisted = runCatching {
                persistenceService.persistDocument(
                    workspaceId = targetWorkspace,
                    document = completedDoc,
                    chunks = embeddedChunks
                )
                true
            }
            if (persisted.getOrDefault(false)) {
                persistenceState = KnowledgePersistenceState.PERSISTED
            } else {
                // One honest retry before declaring failure.
                val retried = runCatching {
                    persistenceService.persistDocument(
                        workspaceId = targetWorkspace,
                        document = completedDoc,
                        chunks = embeddedChunks
                    )
                    true
                }
                if (retried.getOrDefault(false)) {
                    persistenceState = KnowledgePersistenceState.PERSISTED
                } else {
                    persistenceState = KnowledgePersistenceState.FAILED
                    persistenceDiagnostic = "RAG_PERSISTENCE_FAILED: أُدرج المستند في الفهرس الحي لكن تعذّر حفظه في قاعدة البيانات (فشلت محاولتان) — سيفقد المستند عند إعادة تشغيل التطبيق: ${persisted.exceptionOrNull()?.localizedMessage ?: retried.exceptionOrNull()?.localizedMessage ?: "سبب غير معروف"}"
                }
            }
        } else {
            persistenceState = KnowledgePersistenceState.PENDING
            persistenceDiagnostic = "لا يوجد مخزن دائم مهيأ — المستند في الذاكرة فقط."
        }

        completedDoc.copy(
            persistenceState = persistenceState,
            persistenceDiagnostic = persistenceDiagnostic
        )
    }

    /**
     * Resolve the active embedding adapter via the resource pipeline.
     *
     * Returns (adapter, resourceId) where:
     *   - adapter: the resolved `EmbeddingProviderPort` (or null if none available)
     *   - resourceId: the `ResourceId` of the resolved adapter (or null for fallback)
     *
     * Per Phase 4: no silent fallback to a hardcoded default. If no embedding
     * ResourceRecord is registered, the `fallbackEmbeddingProvider` is used
     * (which is the local in-process adapter explicitly injected by
     * `AppContainer`). The fallback path is HONEST — the `RetrievalMode` is
     * `LEXICAL_FALLBACK`, not `HYBRID`.
     */
    private suspend fun resolveEmbeddingProvider(): Pair<EmbeddingProviderPort?, ResourceId?> {
        // Find the first ENABLED HEALTHY embedding ResourceRecord.
        val embeddingResources = resourceRegistry.listResources()
            .filter { it.resourceType == ResourceType.EMBEDDING
                && (it.lifecycleState == com.example.domain.core.resource.ResourceLifecycleState.ENABLED
                    || it.lifecycleState == com.example.domain.core.resource.ResourceLifecycleState.ACTIVE)
                && it.runtimeSupported
                && it.healthStatus != HealthStatus.UNAVAILABLE
            }
        // Prefer the one with HEALTHY health status.
        val chosen = embeddingResources.firstOrNull { it.healthStatus == HealthStatus.HEALTHY }
            ?: embeddingResources.firstOrNull()
        if (chosen != null) {
            val resolution = runtimeAdapterResolver.resolveEmbeddingAdapter(chosen.resourceId)
            val adapter = when (resolution) {
                is Outcome.Success -> resolution.value
                is Outcome.Degraded -> resolution.partialValue
                is Outcome.Error -> null
            }
            if (adapter != null) return adapter to chosen.resourceId
        }
        // Fallback to the injected local adapter. This is HONEST — the
        // `RetrievalMode` will be LEXICAL_FALLBACK, not HYBRID.
        return fallbackEmbeddingProvider to null
    }

    private fun splitIntoChunks(doc: KnowledgeDocument, chunkSize: Int = 300, overlap: Int = 50): List<DocumentChunk> {
        val text = doc.content
        val chunkList = mutableListOf<DocumentChunk>()
        var start = 0
        var chunkIndex = 0
        while (start < text.length) {
            val end = (start + chunkSize).coerceAtMost(text.length)
            val chunkText = text.substring(start, end).trim()
            if (chunkText.isNotBlank()) {
                chunkList.add(
                    DocumentChunk(
                        id = "${doc.id}_c$chunkIndex",
                        documentId = doc.id,
                        documentTitle = doc.title,
                        chunkIndex = chunkIndex,
                        text = chunkText,
                        tokenCount = chunkText.length / 4
                    )
                )
                chunkIndex++
            }
            if (end == text.length) break
            start += (chunkSize - overlap).coerceAtLeast(1)
        }
        return chunkList
    }

    /**
     * Semantic and keyword hybrid search over chunked knowledge base.
     *
     * Audit 2026 fixes:
     *  - retrieval mode is HONEST: a hash-based fallback embedding is labeled
     *    LEXICAL_FALLBACK, not HYBRID (previously any non-null provider was
     *    mislabeled HYBRID even when it produced deterministic hash vectors);
     *  - embedding-compatibility boundary is enforced from chunk metadata
     *    (chunks embedded by a different resource are excluded from semantic
     *    scoring and re-scored lexically instead of silently mixed);
     *  - Arabic normalization applied to queries and lexical scoring;
     *  - proper hybrid fusion: normalized semantic + lexical overlap score,
     *    followed by a lexical rerank of the top candidates.
     */
    /**
     * GAP-CLOSURE P2-05: the retrieval-budget parameter is DEPRECATED on
     * this pipeline entry point — the authoritative retrieval-budget
     * authority is the RagIntelligence layer
     * (domain.core.rag.intelligence.RagRequest.maxTokenBudget), and callers
     * should migrate there. Retained for source compatibility only.
     */
    @Deprecated(
        message = "Retrieval budget authority moved to RagIntelligenceService (RagRequest.maxTokenBudget). Use the parameterless budget overload.",
        replaceWith = ReplaceWith("retrieveRelevantContext(query, topK)")
    )
    suspend fun retrieveRelevantContext(query: String, topK: Int = 4, maxTokenBudget: Int = 2000): AssembledRagContext =
        retrieveRelevantContextInternal(query, topK, RetrievalScopeMode.PROJECT_AND_WORKSPACE)

    suspend fun retrieveRelevantContext(query: String, topK: Int = 4): AssembledRagContext =
        retrieveRelevantContextInternal(query, topK, RetrievalScopeMode.PROJECT_AND_WORKSPACE)

    /**
     * REPAIR ORDER §15 — EXPLICIT retrieval scope mode. The default remains
     * PROJECT_AND_WORKSPACE (backward compatible); callers may tighten to
     * PROJECT_ONLY / WORKSPACE_ONLY / APPLICATION. Cross-project private
     * knowledge is NEVER retrievable regardless of mode (sibling isolation).
     */
    suspend fun retrieveRelevantContext(
        query: String,
        topK: Int = 4,
        scopeMode: RetrievalScopeMode
    ): AssembledRagContext =
        retrieveRelevantContextInternal(query, topK, scopeMode)

    private suspend fun retrieveRelevantContextInternal(
        query: String,
        topK: Int,
        scopeMode: RetrievalScopeMode = RetrievalScopeMode.PROJECT_AND_WORKSPACE
    ): AssembledRagContext = withContext(Dispatchers.Default) {
        val (embeddingProvider, usedResourceId) = resolveEmbeddingProvider()

        // --------------------------------------------------------------
        // REPAIR ORDER §15 — SCOPED RETRIEVAL: resolve the caller's pinned
        // (or active) workspace/project, repair a stale working set, and
        // filter the candidate chunks by the requested SCOPE MODE. This is
        // the structural fix for "retrieval was a GLOBAL working-set scan":
        // another workspace's — or a sibling project's private — knowledge
        // can no longer be silently retrieved.
        // --------------------------------------------------------------
        val retrievalScope = ensureWorkingSetForPinnedScope()
        val pinnedProjectId = retrievalScope?.second
        val scopeFilter: (String) -> Boolean = { documentId ->
            val docProject = docProjectIndex[documentId]
            when (scopeMode) {
                RetrievalScopeMode.PROJECT_ONLY ->
                    pinnedProjectId != null && docProject == pinnedProjectId
                // No pinned project = the caller runs at WORKSPACE scope:
                // the whole (workspace-bounded) working set is visible.
                // With a pinned project: own private + workspace-shared.
                RetrievalScopeMode.PROJECT_AND_WORKSPACE ->
                    pinnedProjectId == null || docProject == null || docProject == pinnedProjectId
                RetrievalScopeMode.WORKSPACE_ONLY -> docProject == null
                RetrievalScopeMode.APPLICATION -> false // no app-shared knowledge persisted yet — honest empty
            }
        }

        val providerIsSemantic = isProviderSemantic(embeddingProvider)

        val queryVector = if (embeddingProvider != null) {
            val outcome = embeddingProvider.generateEmbeddings(listOf(query))
            if (outcome is Outcome.Success) (outcome.value.firstOrNull() ?: generateLexicalVector(query))
            else generateLexicalVector(query)
        } else {
            generateLexicalVector(query)
        }

        val retrievalMode = when {
            embeddingProvider == null -> RetrievalMode.LEXICAL_FALLBACK
            providerIsSemantic -> RetrievalMode.HYBRID
            else -> RetrievalMode.LEXICAL_FALLBACK // hash fallback — honestly labeled
        }

        val normalizedQuery = com.example.infrastructure.memory.semantic.ArabicTextNormalizer.normalize(query)
        val queryTokens = normalizedQuery.lowercase()
            .split(Regex("[^\\w\\d\\u0600-\\u06FF]+")).filter { it.isNotBlank() }.toSet()

        // ------------------------------------------------------------------
        // P1-5 (audit 2026 §29 — retrieval was a FULL re-tokenized scan +
        // two full sorts): the scan now uses the PRECOMPUTED per-chunk index
        // (normalized text + token set — computed once at ingest/load, not
        // per query), a LEXICAL PRE-FILTER (only chunks sharing at least one
        // query token are lexically scored — irrelevant chunks skip token
        // arithmetic entirely), a BOUNDED scan (maxScanChunks; a larger
        // corpus degrades HONESTLY via isTruncated instead of stalling) and
        // a single bounded top-K selection instead of two O(N log N) sorts.
        // ------------------------------------------------------------------
        val candidates = indexedChunks
        val scanBound = minOf(candidates.size, maxScanChunks)
        val scanWasTruncated = candidates.size > maxScanChunks

        // Bounded top-(topK*2) selection via a min-heap of relevance.
        val bound = (topK * 2).coerceAtLeast(2)
        val heap = java.util.PriorityQueue<RetrievedContextChunk>(
            compareBy<RetrievedContextChunk> { it.relevanceScore }
        )

        for (i in 0 until scanBound) {
            val indexed = candidates[i]
            val chunk = indexed.chunk
            // REPAIR ORDER §15 — scope-mode membership check BEFORE any
            // scoring work: out-of-scope chunks (sibling project private,
            // other-workspace) are skipped entirely.
            if (!scopeFilter(chunk.documentId)) continue
            val chunkEmbeddingId = chunk.metadata["embeddingResourceId"]
            // Compatibility boundary: chunks embedded by a DIFFERENT embedding
            // resource than the active one cannot be compared semantically.
            // GAP-07 (Design Closure 2026, ADR-4): the boundary is ALSO
            // dimension-space honest — the local-128 resource can UPGRADE
            // from lexical to ONNX semantic vectors under the SAME resource
            // id (the router seam). A lexical-embedded chunk (metadata
            // embeddingSemantic=false) must never be semantically scored
            // against a semantic query vector (different vector spaces), and
            // vice versa — such chunks stay lexical-scored only, honestly.
            val chunkWasSemantic = chunk.metadata["embeddingSemantic"]?.toBoolean() ?: false
            val vectorCompatible = (chunkEmbeddingId == null ||
                usedResourceId == null ||
                chunkEmbeddingId == usedResourceId.value ||
                chunkEmbeddingId == "local_lexical") &&
                chunkWasSemantic == providerIsSemantic

            val sim = if (vectorCompatible) {
                val chunkVector = chunk.vector ?: generateLexicalVector(chunk.text)
                computeCosineSimilarity(queryVector.values, chunkVector.values)
            } else 0.0f

            // P1-5 LEXICAL PRE-FILTER: with precomputed token sets, a chunk
            // sharing NO query token cannot have a positive lexical F1 — skip
            // the scoring work for it entirely.
            val overlap = if (queryTokens.isEmpty() || indexed.tokens.isEmpty()) 0.0f
            else if (queryTokens.none { it in indexed.tokens }) 0.0f
            else {
                val common = queryTokens.intersect(indexed.tokens).size.toFloat()
                val precision = common / indexed.tokens.size
                val recall = common / queryTokens.size
                if (precision + recall > 0f) 2f * precision * recall / (precision + recall) else 0f
            }

            val semanticWeight = if (vectorCompatible && providerIsSemantic) 0.6f else 0.0f
            val lexicalWeight = 1.0f - semanticWeight
            val combinedScore = (sim * semanticWeight + overlap * lexicalWeight).coerceIn(0.0f, 1.0f)
            if (combinedScore <= 0.05f) continue

            val scored = RetrievedContextChunk(
                chunk = chunk,
                relevanceScore = combinedScore,
                retrievalMode = retrievalMode,
                snippet = chunk.text
            )
            if (heap.size < bound) {
                heap.add(scored)
            } else if (heap.peek().relevanceScore < combinedScore) {
                heap.poll()
                heap.add(scored)
            }
        }

        val scoredChunks = heap.toList()
            .asSequence()
            // Lexical rerank pass: boost candidates whose text actually
            // contains the (normalized) query tokens verbatim.
            .map { scored ->
                val containsBoost = if (scored.chunk.text.contains(query, ignoreCase = true) ||
                    com.example.infrastructure.memory.semantic.ArabicTextNormalizer
                        .normalize(scored.chunk.text).contains(normalizedQuery, ignoreCase = true)
                ) 0.1f else 0.0f
                scored.copy(relevanceScore = (scored.relevanceScore + containsBoost).coerceAtMost(1.0f))
            }
            .sortedByDescending { it.relevanceScore }
            .take(topK)
            .toList()

        val assembledText = buildString {
            appendLine("=== سياق المعرفة المسترجع (RAG Knowledge Base) ===")
            scoredChunks.forEachIndexed { i, c ->
                appendLine("[مصدر ${i + 1}: ${c.chunk.documentTitle} (صلة: ${"%.2f".format(c.relevanceScore)})]")
                appendLine(c.chunk.text)
                appendLine()
            }
        }

        AssembledRagContext(
            query = query,
            formattedContextText = assembledText,
            retrievedChunks = scoredChunks,
            totalTokensEstimated = assembledText.length / 4,
            // P1-5: honest truncation flag when the corpus exceeded the
            // bounded scan (never a silent partial scan).
            isTruncated = scanWasTruncated
        )
    }

    /**
     * TRUE only when the embedding provider actually produces semantic
     * vectors (a trained model — e.g. ONNX MiniLM or a cloud embedding API).
     * The deterministic hash fallback is NOT semantic and is labeled as such.
     */
    private fun isProviderSemantic(provider: EmbeddingProviderPort?): Boolean {
        if (provider == null) return false
        return (provider as? com.example.infrastructure.memory.semantic.EmbeddingQualityMarker)?.isSemantic ?: true
    }

    private fun generateLexicalVector(text: String): EmbeddingVector {
        val tokens = text.lowercase().split(Regex("[^\\w\\d]+")).filter { it.isNotBlank() }
        val vector = FloatArray(32) { 0.0f }
        for (token in tokens) {
            val hash = (token.hashCode() and 0x7FFFFFFF) % 32
            vector[hash] += 1.0f
        }
        val norm = sqrt(vector.sumOf { (it * it).toDouble() }).toFloat()
        if (norm > 0.001f) {
            for (i in vector.indices) vector[i] /= norm
        }
        return EmbeddingVector(vector)
    }

    private fun computeCosineSimilarity(vecA: FloatArray, vecB: FloatArray): Float {
        val len = minOf(vecA.size, vecB.size)
        if (len == 0) return 0.0f
        var dot = 0.0f
        var nA = 0.0f
        var nB = 0.0f
        for (i in 0 until len) {
            dot += vecA[i] * vecB[i]
            nA += vecA[i] * vecA[i]
            nB += vecB[i] * vecB[i]
        }
        val denom = (sqrt(nA.toDouble()) * sqrt(nB.toDouble())).toFloat()
        return if (denom > 1e-6f) (dot / denom).coerceIn(-1.0f, 1.0f) else 0.0f
    }
}
